In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1D Array
array1 = np.array([10, 20, 30, 40, 50])

# 2D Array
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Array
array3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("1D Array")
print(array1)
print("Shape:", array1.shape)

print("\n2D Array")
print(array2)
print("Shape:", array2.shape)

print("\n3D Array")
print(array3)
print("Shape:", array3.shape)

1D Array
[10 20 30 40 50]
Shape: (5,)

2D Array
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [3]:
array = np.array([1,2,3,4,5])

result = array + 10

print("Original Array")
print(array)

print("\nAfter Broadcasting")
print(result)

Original Array
[1 2 3 4 5]

After Broadcasting
[11 12 13 14 15]


In [4]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

print("Addition")
print(a + b)

print("\nSubtraction")
print(b - a)

print("\nMultiplication")
print(a * b)

print("\nDivision")
print(b / a)

Addition
[11 22 33 44 55]

Subtraction
[ 9 18 27 36 45]

Multiplication
[ 10  40  90 160 250]

Division
[10. 10. 10. 10. 10.]


In [5]:
matrix1 = np.array([
    [1,2],
    [3,4]
])

matrix2 = np.array([
    [5,6],
    [7,8]
])

result = np.matmul(matrix1, matrix2)

print("Matrix Multiplication")
print(result)

Matrix Multiplication
[[19 22]
 [43 50]]


In [6]:
data = {
    "Age":[21,25,28,30,35],
    "Salary":[30000,35000,40000,50000,60000],
    "Experience":[1,3,5,7,10]
}

df = pd.DataFrame(data)

df.to_csv("employee.csv", index=False)

print(df)

   Age  Salary  Experience
0   21   30000           1
1   25   35000           3
2   28   40000           5
3   30   50000           7
4   35   60000          10


In [7]:
data = pd.read_csv("employee.csv")

print("Dataset")
print(data)

print("\nMean")
print(data.mean())

print("\nStandard Deviation")
print(data.std())

print("\nCorrelation")
print(data.corr())

Dataset
   Age  Salary  Experience
0   21   30000           1
1   25   35000           3
2   28   40000           5
3   30   50000           7
4   35   60000          10

Mean
Age              27.8
Salary        43000.0
Experience        5.2
dtype: float64

Standard Deviation
Age               5.263079
Salary        12041.594579
Experience        3.492850
dtype: float64

Correlation
                 Age    Salary  Experience
Age         1.000000  0.978290    0.995477
Salary      0.978290  1.000000    0.992642
Experience  0.995477  0.992642    1.000000


In [ ]:
Observations:

1. Created 1D, 2D and 3D NumPy arrays successfully.
2. Verified the shape of each array.
3. Performed broadcasting without using loops.
4. Used vectorized operations for arithmetic calculations.
5. Performed matrix multiplication using NumPy.
6. Calculated mean, standard deviation and correlation on a sample CSV dataset.