In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1D Array
array1 = np.array([10, 20, 30, 40, 50])

# 2D Array
array2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Array
array3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("1D Array")
print(array1)
print("Shape:", array1.shape)

print("\n2D Array")
print(array2)
print("Shape:", array2.shape)

print("\n3D Array")
print(array3)
print("Shape:", array3.shape)

1D Array
[10 20 30 40 50]
Shape: (5,)

2D Array
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [3]:
array = np.array([1,2,3,4,5])

result = array + 10

print("Original Array")
print(array)

print("\nAfter Broadcasting")
print(result)

Original Array
[1 2 3 4 5]

After Broadcasting
[11 12 13 14 15]


In [4]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])

print("Addition")
print(a + b)

print("\nSubtraction")
print(b - a)

print("\nMultiplication")
print(a * b)

print("\nDivision")
print(b / a)

Addition
[11 22 33 44 55]

Subtraction
[ 9 18 27 36 45]

Multiplication
[ 10  40  90 160 250]

Division
[10. 10. 10. 10. 10.]
